FROM mcr.microsoft.com/dotnet/core/runtime:3.1-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build
WORKDIR /src

COPY src/ConsoleApp/*.csproj ./ConsoleApp/
COPY src/Domain/*.csproj ./Domain/
COPY src/Infrastructure/*.csproj ./Infrastructure/

RUN dotnet restore /src/ConsoleApp/ConsoleApp.csproj

COPY src/ .

RUN dotnet build "/src/ConsoleApp/ConsoleApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "/src/ConsoleApp/ConsoleApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "ConsoleApp.dll"]