version: '3.2'

services:
  postgres:
    image: postgres:10
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - connectorpgdata:/var/lib/postgresql/data
    networks:
      - connectornetwork
    restart: on-failure
    
  connector:
    build:
      context: ./
      dockerfile: Dockerfile.consoleapp
    image: ${CONNECTOR_IMAGE}
    restart: on-failure
    networks:
      - connectornetwork
    depends_on:
      - postgres
    
volumes:
  connectorpgdata:
  
networks:
  connectornetwork:
     driver: bridge