version: '3.2'

services:
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    env_file: ./db.env
    environment:
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: always
	  
volumes:
  pgdata:

networks:
  default:
    external:
      name: connectors-overlay
